#!/usr/bin/expect

set host [ lindex $argv 0 ]
set password [ lindex $argv 1 ]
set src_file [ lindex $argv 2 ]

set timeout 10


spawn scp $src_file root@$host:/tmp/id_rsa.pub
expect {
	"*yes/no" { send "yes\r"; exp_continue}
	"*password:" { send "$password\r" }
}


spawn ssh $host
expect {
	"*yes/no" { send "yes\r"; exp_continue}
	"*password:" { send "$password\r" }
}
expect "~*"	
send "cat /tmp/id_rsa.pub  >> /root/.ssh/authorized_keys\r"
send  "exit\r"
expect eof
